---
output:
  html_document:
    toc: true
    toc_float: true
---

# Education

---

### Columbia University, Mailman School of Public Health

**Master of Public Health (MPH), Epidemiology | Certificate in Epidemiology of Chronic Diseases | Expected May 2020**

•	Coursework included: Data Science II, Relational Databases and SQL Programming for Research and Data Science, Latent Variable and Structural Equation Modeling, Neurological Epidemiology, Data Science I, Applied Regression I, Applied Data Analysis for Epidemiology, Applications of Epidemiological Research Methods, Design & Conduct of Observational Studies, Health Economics, US Health Systems, Analysis of Categorical Data, Quantitative and Qualitative research methods.  

•	Activities & Societies: VP of Communications - Healthcare Data Analytics, VP of Events - Queer Health Task Force.

### Gujarat University, Karnavati School of Dentistry

**Bachelor of Dental Surgery (BDS) | September 2012 – September 2017**

•	U.S. Equivalency (W.E.S.) - Five years of professional study in dentistry at an accredited institution. 

# Professional Experience 

---

### Columbia Aging Center

**Graduate Research Assistant --- February 2020 – Present**

•	Analyzed socio-genomic data for measurement of lifecourse aging.

### Columbia University, Department of Epidemiology

**Graduate Research Assistant --- October 2019 – February 2020**

•	Geocoded 400+ streets for tobacco retail sites and advertisements in Indonesia using Google Street View.

### Research Foundation for Mental Hygiene, New York State Psychiatric Institute 

**Research Assistant --- October 2019 – December 2019**

•	Conducted factorial survey data analysis in R for vignette experiments evaluating effect of genetic evidence and psychiatric history on decision making in tort litigation cases among 500 judges for the Department of Law, Ethics and Psychiatry.


### Columbia University, Department of Epidemiology  

**Graduate Research Assistant --- June 2019–August 2019** 

•	Data cleaning and analysis using predictive modeling and machine learning on NYC birth cohort of 1994-1998 with 201,559 observations and 207 variables in R.

•	Assessed joint effects of blood lead and 40 air pollutants on 3rd grade test scores in the birth cohort.  

•	Developed a causal hypothesis for a retrospective observational study using DAGs in Daggity.


### Columbia University, School of Nursing

**Graduate Research Assistant --- December 2018–May 2019**

•	Data collection, study design and analysis assistant for a NIH (NINR) grant funded project exploring associations between antibiotic use and NH resident self-reported or family reported resident symptoms in SAS. 

•	Abstraction of EMR data and administration of surveys in REDCap for data collection.


### Smt. Sushilaben Kothari Charitable Hospital

**Consultant Dentist --- October 2017–August 2018**

•	Leading dental health check-up camps involving 150+ patients and performing treatments in over 60% patients. 

•	Introduced tobacco cessation program leading to increase in fidelity levels by 30% in rural Ahmedabad in 6 months.

•	Successfully managed patient records and accounts.

### Karnavati School of Dentistry

**Intern Dentist --- September 2016–October 2017**

•	Performing routine dental checkups. 

•	Prescribing drugs and performing relevant treatments such as scaling, RCT, crown & bridge, complete dentures

•	Counselling regarding oral health hygiene and addiction.

### Vakharia Dental Hospital

**Management Intern	--- January 2017–March 2017**

•	Data entry and management of patient records and accounts

•	Telecommunications, scheduling and managing appointments

### Karnavati School of Dentistry 

**Research Assistant --- November 2016–January 2017**

•	Data collection and analysis assistant in the Department of Oral Medicine for a case-control study on the effects of glossectomy and radiation therapy in middle-aged women treated for carcinoma of tongue in Kalol.

### Karnavati School of Dentistry

**Teaching Assistant --- September 2013–July 2014**

•	Assisted in development of dental anatomy and histology course for first-year dental surgery students. 

•	Distributed course materials, supervised class room and lab sessions of about 40 students and graded assignment and papers

# Awards & Honors 

---

### Poster Presentation Award: Environmental Epidemiology 

**Columbia University, Department of Epidemiology	--- October 2019** 

•	Assessing joint effects of blood lead and air pollution on children’s 3rd grade standardized test scores in New York City birth cohort from 1994 to 1998.

# Software Skills 

---

R, SQL, SAS, MPlus, QGIS, MS Excel, MS PowerPoint, MS Word. 

# Languages

---

English, Hindi, Gujarati, Spanish. 

# Certifications 

---

HIPAA, CITI, BLS


